version: '3.8'
services:
  stock-service:
    build: ./stock-service
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    volumes:
      - ./stock-service/logs:/root/logs
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - ENV=development